- frontend/app/(pages)/register-farm/page.tsx
- frontend/components/forms/FarmRegistrationForm.tsx
Feat: Add Farm Registration Form and API Endpoint
Related Issue: Closes #13 
Description
This pull request introduces the complete feature for farm registration. It includes a new page where farmers can submit their farm details, a modern and user-friendly React component for the form itself, and the corresponding API endpoint to handle the data submission.
The primary goal is to provide a seamless and intuitive way for users to register their farm information, which is a core requirement for the application.
Changes Made
API Endpoint (/api/farms)
Created a new API route at app/api/farms/route.ts.
It currently accepts POST requests with the farm data (cropType, size, location, plantingSeason).
For now, it simulates a successful response and returns the submitted data. (Note: Database …
> Feat: Add Farm Registration Form and API Endpoint

- frontend/app/(pages)/auth/page.tsx
- frontend/app/(pages)/register-farm/page.tsx
- frontend/app/page.tsx
- frontend/components/forms/AuthForm.tsx
- frontend/components/forms/FarmRegistrationForm.tsx
- frontend/components/landing/Home.tsx
- frontend/next.config.ts
- frontend/package-lock.json
- frontend/package.json
Feat: Implement Modern Landing Page for SmartFarmPro
Related Issue: Closes #10 
Description
This pull request introduces a comprehensive, modern, and fully responsive landing page for the SmartFarmPro application. The goal is to create a compelling entry point for new visitors that clearly communicates the platform's value proposition, focusing on its AI and blockchain capabilities for Nigerian farmers.
This page serves as the new public face of the application and is designed to drive user registration.
Changes Made
1. New Landing Page (app/page.tsx)
The root page.tsx has been transformed into the main landing page.
Hero Section: Features a powerful headline, descriptive subtext, and a prominent "Get Started" call-to-action (CTA) button, all set against an inspiring farm backdrop. …
> Feat: Implement Modern Landing Page for SmartFarmPro

- backend/package-lock.json
- backend/src/app.module.ts
- backend/src/suppliers/dto/create-supplier.dto.ts
- backend/src/suppliers/dto/search-suppliers.dto.ts
- backend/src/suppliers/dto/update-supplier.dto.ts
- backend/src/suppliers/entities/supplier.entity.ts
- backend/src/suppliers/suppliers.controller.ts
- backend/src/suppliers/suppliers.module.ts
- backend/src/suppliers/suppliers.service.ts
Closes #51: Add Suppliers Module for Location-Based Supplier Discovery
Overview
Implemented a comprehensive suppliers module that enables farmers to find and list nearby suppliers of agricultural products based on location data. The module operates independently without dependencies on other application modules.
Key Features
Location-based search: Find suppliers within specified radius using GPS coordinates
Product filtering: Search suppliers by specific agricultural products
Distance calculation: Uses Haversine formula for accurate distance measurements
Rating system: Suppliers include ratings and review counts for quality assessment
Flexible sorting: Sort results by distance, rating, or name
Geographic filtering: Additional filters by city and state
Seed data: Includes sample Nigerian …
> Implement Suppliers module with CRUD operations and search functionality

- backend/src/app.module.ts
- backend/src/utils/gps.controller.ts
- backend/src/utils/gps.service.spec.ts
- backend/src/utils/gps.service.ts
- backend/src/utils/utils.module.ts
Implements a comprehensive GPS utility module that converts GPS coordinates to defined Nigerian farming regions, supporting the FarmAssist platform's location-based features.
- ✅ **GPS to Region Conversion**: Convert latitude/longitude to predefined farming regions
- ✅ **Distance Calculation**: Haversine formula implementation for accurate distance measurement
- ✅ **Nearest Region Finder**: Find closest farming region when coordinates fall outside defined areas
- ✅ **Region Management**: Get regions by ID, state, or retrieve all regions
- ✅ **RESTful API**: Complete HTTP endpoints for all functionality
- ✅ **Input Validation**: Comprehensive validation for coordinates and parameters
- ✅ **Unit Testing**: Full test coverage for all service methods
- Kaduna South (Guinea Savanna)
- Kano …
> feat: implement GPS coordinates to farming region utility module

- backend/src/app.module.ts
- backend/src/user-preferences/dto/create-user-preferences.dto.ts
- backend/src/user-preferences/dto/update-user-preferences.dto.ts
- backend/src/user-preferences/entities/user-preferences.entity.ts
- backend/src/user-preferences/user-preferences.controller.ts
- backend/src/user-preferences/user-preferences.module.ts
- backend/src/user-preferences/user-preferences.service.ts
> User Preference Module

- backend/src/app.module.ts
- backend/src/purchase-tracking/dto/create-purchase-tracking.dto.ts
- backend/src/purchase-tracking/dto/query-purchase-records.dto.ts
- backend/src/purchase-tracking/dto/update-purchase-tracking.dto.ts
- backend/src/purchase-tracking/entities/purchase-tracking.entity.ts
- backend/src/purchase-tracking/purchase-tracking.controller.spec.ts
- backend/src/purchase-tracking/purchase-tracking.controller.ts
- backend/src/purchase-tracking/purchase-tracking.module.ts
- backend/src/purchase-tracking/purchase-tracking.service.spec.ts
- backend/src/purchase-tracking/purchase-tracking.service.ts
I've created a comprehensive, fully independent purchase recording module for your NestJS application. Here's what the module includes:
Key Features:
1. Complete Purchase Tracking:
Records every purchase with timestamps
Stores detailed item information (name, price, quantity, SKU, etc.)
Tracks transaction IDs to prevent duplicates
Supports multiple currencies and payment methods
2. Database Entity:
Uses UUID primary keys for better scalability
JSONB storage for flexible item details and metadata
Proper indexing for performance
Automatic timestamps (created_at, updated_at)
3. Robust API Endpoints:
POST /purchase-records - Record new purchases
GET /purchase-records - List all purchases with filtering
GET /purchase-records/user/:userId - Get user-specific purchases
GET /purchase-records/:id …
> purchase tracking feature implemented

- backend/src/app.module.ts
- backend/src/inventory-stock/dto/createInventoryStockDto.ts
- backend/src/inventory-stock/dto/updateInventoryStockDto.ts
- backend/src/inventory-stock/inventory-stock.entity.ts
- backend/src/inventory-stock/inventory-stock.module.ts
- backend/src/inventory-stock/inventory-stock.service.ts
- backend/src/inventory-stock/inventoryStock.controller.ts
This PR introduces the Inventory Tracking Module to the backend, enabling tracking of current input stock (e.g., fertilizer, seed packets) for each farmer.
- Added `InventoryTrackingModule` with:
- Entity: `InventoryStock`
- DTOs: `CreateInventoryStockDto`, `UpdateInventoryStockDto`
- Service: `InventoryTrackingService`
- Controller: `InventoryTrackingController`
- Module: `InventoryTrackingModule`
- Registered the module in `app.module.ts` for integration.
- Endpoints support:
- Create inventory record
- Update inventory record
- List all inventory records
- List inventory records by farmer
- All naming and references updated for consistency and isolation.
- Implementation is isolated for easy future extension.
- Uses in-memory storage for now; ready for database integration via TypeORM. …
> feat/ Implemented  Inventory Tracking Module for Farm Input Stock Management

- backend/src/animal-feed/animal-feed.controller.ts
- backend/src/animal-feed/animal-feed.entity.ts
- backend/src/animal-feed/animal-feed.module.ts
- backend/src/animal-feed/animal-feed.service.ts
- backend/src/animal-feed/dto/create-animal-feed.dto.ts
- backend/src/animal-feed/dto/update-animal-feed.dto.ts
- backend/src/app.module.ts
close #32 
- Adds a self-contained `animal-feed` module to manage feed types, nutrition data, recommended species, and storage requirements.
- Full CRUD with validation and TypeORM (Postgres) persistence.
- Registers module in [app.module.ts](cci:7://file:///Users/mustang/Desktop/FarmAssist/backend/src/app.module.ts:0:0-0:0) and fixes incorrect purchase module import name.
- Entity: [backend/src/animal-feed/animal-feed.entity.ts](cci:7://file:///Users/mustang/Desktop/FarmAssist/backend/src/animal-feed/animal-feed.entity.ts:0:0-0:0)
- DTOs:
- [backend/src/animal-feed/dto/create-animal-feed.dto.ts](cci:7://file:///Users/mustang/Desktop/FarmAssist/backend/src/animal-feed/dto/create-animal-feed.dto.ts:0:0-0:0)
- [backend/src/animal-feed/dto/update-animal-feed.dto.ts](cci:7://file:///Users/must …
> feat: Add standalone Animal Feed CRUD module (NestJS)

- backend/src/recommendations/recommendations.controller.spec.ts
- backend/src/recommendations/recommendations.controller.ts
- backend/src/recommendations/recommendations.module.ts
- backend/src/recommendations/recommendations.service.spec.ts
- backend/src/recommendations/recommendations.service.ts
PR: feat(recommendations): Create Smart Input Recommendation Stub Endpoint
Closes #5 
Description
This pull request introduces a new stub endpoint for providing smart input recommendations to users based on their farm details. It creates a dummy recommendation engine that suggests agricultural inputs (like fertilizer and seeds) based on a farm's registered crop type and size.
This feature is foundational for building out a more advanced, data-driven recommendation system in the future.
Implementation Details
POST /recommendations/:farmId: A new GET endpoint that accepts a farmId as a URL parameter.
RecommendationsModule: A new module created to encapsulate all recommendation-related logic.
RecommendationsService: Contains the core business logic. It uses a mock data array of farms and …
> PR: feat(recommendations): Create Smart Input Recommendation Stub Endpoint

- backend/src/farms/dto/create-farm.dto.ts
- backend/src/farms/entities/farm.entity.ts
- backend/src/farms/farm.controller.spec.ts
- backend/src/farms/farm.controller.ts
- backend/src/farms/farm.module.ts
- backend/src/farms/farm.service.spec.ts
- backend/src/farms/farm.service.ts
- backend/src/recommendations/entity/recommendation.entity.ts
- backend/src/recommendations/recommendations.controller.spec.ts
- backend/src/recommendations/recommendations.controller.ts
- backend/src/recommendations/recommendations.module.ts
- backend/src/recommendations/recommendations.service.spec.ts
- backend/src/recommendations/recommendations.service.ts
- backend/src/vendors/controller.spec.ts
- backend/src/vendors/dto/create-vendor.dto.ts
- backend/src/vendors/dto/update-vendor.dto.ts
- backend/src/vendors/entities/vendor.entity.ts
- backend/src/vendors/service.spec.ts
- backend/src/vendors/vendors.controller.ts
- backend/src/vendors/vendors.module.ts
- backend/src/vendors/vendors.service.ts
**Closes #2**
This pull request introduces the foundational database layer for the application by defining all core business entities using TypeORM. It migrates the application from an in-memory data store to a persistent PostgreSQL database, which is a critical step for enabling robust data storage and scalability.
The schema includes entities for `User`, `Farm`, `Vendor`, `Input`, and `Recommendation`, with clearly defined relationships between them.
-   **Entities Created**:
-   `User`: Represents application users with roles (`farmer`, `admin`).
-   `Farm`: Represents farms registered by users.
-   `Vendor`: Represents suppliers of agricultural inputs.
-   `Input`: Represents the products sold by vendors.
-   `Recommendation`: A simple entity to store generated recommendations.
- …
> feat(database): Design TypeORM Entities and Relationships

- backend/src/app.module.ts
- backend/src/equipment-marketplace/dto/create-equipment-listing.dto.ts
- backend/src/equipment-marketplace/dto/query-equipment-listings.dto.ts
- backend/src/equipment-marketplace/dto/update-equipment-listing.dto.ts
- backend/src/equipment-marketplace/entities/equipment-listing.entity.ts
- backend/src/equipment-marketplace/enums/equipment-type.enum.ts
- backend/src/equipment-marketplace/enums/listing-status.enum.ts
- backend/src/equipment-marketplace/equipment-marketplace.controller.ts
- backend/src/equipment-marketplace/equipment-marketplace.module.ts
- backend/src/equipment-marketplace/equipment-marketplace.service.spec.ts
- backend/src/equipment-marketplace/equipment-marketplace.service.ts
- backend/src/input-price-tracker/dto/create-input-price.dto.ts
- backend/src/input-price-tracker/dto/query-price-history.dto.ts
- backend/src/input-price-tracker/dto/update-input-price.dto.ts
- backend/src/input-price-tracker/entities/input-price.entity.ts
- backend/src/input-price-tracker/enums/aggregate-function.enum.ts
- backend/src/input-price-tracker/enums/input-type.enum.ts
- backend/src/input-price-tracker/enums/price-frequency.enum.ts
- backend/src/input-price-tracker/input-price-tracker.controller.ts
- backend/src/input-price-tracker/input-price-tracker.module.ts
- backend/src/input-price-tracker/input-price-tracker.service.spec.ts
- backend/src/input-price-tracker/input-price-tracker.service.ts
This PR introduces the **Equipment Marketplace Module**, a standalone backend module that allows listing farming equipment available for **sale** or **rent**. The module is designed to be fully **self-contained** and independent from other parts of the system.
The module provides functionality to:
- Create, update, and manage equipment listings.
- Include fields like:
- `id`
- `name`
- `type` (e.g., tractor, harvester, plow)
- `price`
- `location`
- `availabilityStatus` (e.g., available, sold, rented)
- Retrieve equipment based on filters like type, location, price range, and availability.
- Support pagination and sorting for large datasets.
- Added a new `equipment-marketplace` module.
- **Entity**: `Equipment` with fields:
- `id`
- `name`
- `type`
- `price`
- `location`
- …
> Feat equipmet marketplace

- backend/src/app.module.ts
- backend/src/recommendation-logging/dto/create-recommendation-log.dto.ts
- backend/src/recommendation-logging/dto/update-outcome.dto.ts
- backend/src/recommendation-logging/entities/recommendation-log.entity.ts
- backend/src/recommendation-logging/recommendation-logging.controller.ts
- backend/src/recommendation-logging/recommendation-logging.module.ts
- backend/src/recommendation-logging/recommendation-logging.service.ts
Implements a comprehensive recommendation logging system that tracks all recommendations made by the FarmAssist platform with timestamps, user information, and outcome tracking.
- **Comprehensive Logging**: Tracks fertilizer, seed, farm input, advisory, and crop suggestion recommendations
- **Outcome Tracking**: Monitor recommendation effectiveness with status updates
- **Analytics**: Statistics endpoints for insights and reporting
- **Flexible Querying**: Filter by user, farm, date range, recommendation type, and outcome
- **Modular Design**: Standalone service that integrates seamlessly with existing modules
- **Entity**: `RecommendationLog` with comprehensive fields for tracking
- **Service**: `RecommendationLoggingService` with logging, querying, and analytics methods
- …
> feat: implement standalone recommendation logging module

- backend/src/farm-activity/dto/create-farm-activity.dto.ts
- backend/src/farm-activity/dto/update-farm-activity.dto.ts
- backend/src/farm-activity/entities/activity-log.entity.ts
- backend/src/farm-activity/entities/activity.entity.ts
- backend/src/farm-activity/farm-activity.controller.ts
- backend/src/farm-activity/farm-activity.module.ts
- backend/src/farm-activity/farm-activity.service.ts
- backend/src/farm-activity/repositories/activity.repository.ts
- backend/src/farm-activity/repositories/memory-activity.repository.ts
This task introduces a new module to track and log various farm activities. The module is implemented as a standalone component to ensure modularity and reusability.
It logs key actions such as planting, watering, and feeding animals, providing a foundation for future features like activity history and reporting.
Closes #46
> feat: Add farm activity logger module

- contract/DisputeResolution.sol
Closes #73 
This pull request introduces **`DisputeResolution.sol`**, a standalone smart contract that establishes a basic governance mechanism for farmers to vote on community disputes.
The contract allows any user to create a dispute, and any other user to cast a vote of **"For"** or **"Against"**.  
This system creates a transparent and on-chain record of community sentiment regarding issues like false recommendations or faulty products.
---
- **State**:  
A `Dispute` struct is used to store all relevant information, including the description, creator, vote counts, and resolved status.
- **Dispute Creation**:  
`createDispute(string calldata _description)` allows any user to raise a new issue, which is assigned a unique ID.
- **Voting Mechanism**:  
`vote(uint256 _disputeId, VoteOption …
> feat(governance): Implement Dispute Resolution Voting Contract

- backend/package-lock.json
- backend/package.json
- backend/src/reviews/dto/create-review.dto.ts
- backend/src/reviews/dto/update-review.dto.ts
- backend/src/reviews/entities/review.entity.ts
- backend/src/reviews/reviews.controller.ts
- backend/src/reviews/reviews.module.ts
- backend/src/reviews/reviews.service.ts
> Implemented Product Rating & Review Module

- backend/package-lock.json
- backend/package.json
- backend/src/farm-budget/dto/estimate-budget.dto.ts
- backend/src/farm-budget/dto/farm-budget.service.ts
- backend/src/farm-budget/farm-budget.controller.ts
- backend/src/farm-budget/farm-budget.module.ts
- backend/src/reviews/dto/create-review.dto.ts
- backend/src/reviews/dto/update-review.dto.ts
- backend/src/reviews/entities/review.entity.ts
- backend/src/reviews/reviews.controller.ts
- backend/src/reviews/reviews.module.ts
- backend/src/reviews/reviews.service.ts
> Farm Budget Estimator Module

- backend/src/app.module.ts
- backend/src/crops/crops.controller.ts
- backend/src/crops/crops.module.ts
- backend/src/crops/crops.service.spec.ts
- backend/src/crops/crops.service.ts
- backend/src/crops/dto/create-crop.dto.ts
- backend/src/crops/dto/query-crops.dto.ts
- backend/src/crops/dto/update-crop.dto.ts
- backend/src/crops/entities/crop.entity.ts
- backend/src/seed-demand-predictor/README.md
- backend/src/seed-demand-predictor/dto/create-seed-usage.dto.ts
- backend/src/seed-demand-predictor/dto/prediction-query.dto.ts
- backend/src/seed-demand-predictor/dto/update-seed-usage.dto.ts
- backend/src/seed-demand-predictor/entities/seed-usage.entity.ts
- backend/src/seed-demand-predictor/seed-demand-predictor.controller.spec.ts
- backend/src/seed-demand-predictor/seed-demand-predictor.controller.ts
- backend/src/seed-demand-predictor/seed-demand-predictor.module.ts
- backend/src/seed-demand-predictor/seed-demand-predictor.service.spec.ts
- backend/src/seed-demand-predictor/seed-demand-predictor.service.ts
- backend/src/seed-demand-predictor/types/prediction.types.ts
- backend/test/crops.e2e-spec.ts
This PR introduces the **Crops Database Module**, a fully standalone module for storing and managing metadata about various crops.  
It enables storage and retrieval of information such as planting season, growth cycle, and common diseases.
---
- Implemented `CropsDatabaseModule` for crop-related metadata.  
- Added services to:  
- Store metadata for different crop types.  
- Retrieve metadata for specific crops.  
- Update and delete crop information.  
- Designed to be **self-contained and independent** of other modules.  
---
- Standalone module with no external dependencies.  
- Core functionalities:  
- Create crop records with detailed metadata.  
- Update existing crop metadata.  
- Delete crop records.  
- Retrieve metadata for specific crops or list all crops.  
- `Crop`
- `id: …
> Feat crop database

- backend/package-lock.json
- backend/package.json
- backend/src/auth/auth.service.spec.ts
- backend/src/farms/farm.service.spec.ts
- backend/src/user-preferences/user.service.spec.ts
This PR adds unit tests to `auth`, `users` and `feat` module
Closes #9
> feat: write unit tests core module

- contract/ProductTraceability.sol
This PR introduces a Batch-level Traceability Contract that enables tracking of a product’s origin, manufacturing date, and supply chain checkpoints. The implementation uses event logs and/or structured storage to ensure transparency and auditability across the supply chain. The contract is designed to function independently, allowing modular integration with other systems.
closes #75
> feat: implement ProductTraceability contract for supply chain tracking

- contract/.gitIgnore
- contract/RewardPoints.sol
- contract/node_modules/.package-lock.json
- contract/package-lock.json
- contract/package.json
**Closes #69**
This pull request introduces `RewardPoints.sol`, a standalone smart contract that establishes a transparent and auditable on-chain loyalty program. It allows the platform to award points to users (e.g., farmers) for making frequent or bulk purchases.
Users can accumulate these points in their wallet address and redeem them, creating a strong incentive for repeat business and customer loyalty. The contract is self-contained and managed by an administrative owner.
---
-   **State Management**: A `mapping(address => uint256)` is used to track the points balance of each user.
-   **Access Control**: The contract inherits from OpenZeppelin's `Ownable`, ensuring that only a designated owner (the administrator) can perform critical functions like awarding points.
-   **Core …
> feat(contracts): implement reward points contract for consistent buyers
